server:
    port: 9091


spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/wms?characterEncoding=UTF-8
        username: root
        password: xxy123..
        driver-class: com.mysql.jdbc.Driver

